/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

const result = fibonaccis()
    .filter(fib => fib % 2 === 0)
    .reduce((a, b) => a + b, 0);

console.log(`Result: ${result}`);

/**
 * Fibonacci, recursive
 *
 * @param arr
 * @param max
 * @returns {*}
 */
function fibonaccis(arr = [0, 1], max = 4000000) {
    const n = arr[arr.length - 1] + arr[arr.length - 2];

    if (n > max) return arr;

    arr.push(n);
    return fibonaccis(arr, max);
}
