/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

import MathUtils from '../utils/math';

const result = MathUtils.fibonaccis(4000000)
    .filter(fib => fib % 2 === 0)
    .reduce((a, b) => a + b, 0);

console.log(`Result: ${result}`);
